# Generated by Django 5.1.4 on 2025-01-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('prescription', 'Prescription'), ('lab_result', 'Lab Result')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
